### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gassechen** [Lovesan/bike#9]
sbcl 2.0.0
dotnet-sdk-6.0.20
.Net exception System.BadImageFormatException
Could not load file or assembly 'System.IO.Compression.Native, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at lambda_method10(Closure , IntPtr , IntPtr& , Int32& , IntPtr& )
   [Condition of type BIKE:DOTNET-ERROR]

Restarts:
 0: [TRY-RECOMPILING] Recompile assemblies and try loading it again
 1: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "bike" "src" "assemblies">.
 2: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "bike" "src" "assemblies"> as having been successful.
 3: [RETRY] Retry ASDF operation.
 4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 5: [RETRY] Retry ASDF operation.
 --more--

**Comment by Lovesan** [comment]
Well, need to check this out

**Comment by Lovesan** [comment]
Fixed
